### ISSUE TITLE
Link Maven dependency

### ISSUE THREAD

**Issue by janheinrichmerker** [terrierteam/jtreceval#3]
Would be great to have the Maven dependency linked in the readme:
https://search.maven.org/artifact/uk.ac.gla.dcs.terrierteam/jtreceval

**Comment by janheinrichmerker** [comment]
We could include a badge like this:
![Maven Central](https://img.shields.io/maven-central/v/uk.ac.gla.dcs.terrierteam/jtreceval)
That could also be linked to the central repository:
[![Maven Central](https://img.shields.io/maven-central/v/uk.ac.gla.dcs.terrierteam/jtreceval)](https://search.maven.org/artifact/uk.ac.gla.dcs.terrierteam/jtreceval)

**Comment by cmacdonald** [comment]
great. Can you send a PR?

**Comment by cmacdonald** [comment]
Thanks for all of your contributions @heinrichreimer - glad you are finding jtreceval useful.
